version: "3.8"
services:
  backend:
    build: .
    command: uvicorn backend:app --host 0.0.0.0 --port 9999
    ports:
      - "9999:9999"
    env_file:
      - .env

  frontend:
    build: .
    command: streamlit run frontend.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
